"""Leak-resistant contracts for Versioned Structural Memory Transactions."""

from .baselines import (
    ELUAdapter,
    ELUConfig,
    LOWAdapter,
    LOWConfig,
    TAFAdapter,
    TAFConfig,
    WFRAdapter,
    WFRConfig,
)

from .contracts import (
    AdapterInput,
    MemoryUpdateAdapter,
    build_adapter_input,
    canonical_sha256,
    load_private_evaluation,
    load_public_observation,
    run_adapter,
    seal_candidate_catalog,
    seal_private_evaluation,
    seal_teacher_targets,
    validate_candidate_catalog,
    validate_memory_update_result,
    validate_observation_packet,
    validate_private_evaluation,
    validate_private_mutation_invariance,
    validate_teacher_targets,
)
from .public_candidates import (
    PublicCandidateConfig,
    generate_public_candidate_catalog,
    label_sealed_candidates,
)

__all__ = [
    "AdapterInput",
    "MemoryUpdateAdapter",
    "build_adapter_input",
    "canonical_sha256",
    "load_private_evaluation",
    "load_public_observation",
    "run_adapter",
    "seal_candidate_catalog",
    "seal_private_evaluation",
    "seal_teacher_targets",
    "validate_candidate_catalog",
    "validate_memory_update_result",
    "validate_observation_packet",
    "validate_private_evaluation",
    "validate_private_mutation_invariance",
    "validate_teacher_targets",
    "ELUAdapter",
    "ELUConfig",
    "LOWAdapter",
    "LOWConfig",
    "TAFAdapter",
    "TAFConfig",
    "WFRAdapter",
    "WFRConfig",
    "PublicCandidateConfig",
    "generate_public_candidate_catalog",
    "label_sealed_candidates",
]
