"""Leak-resistant contracts for Versioned Structural Memory Transactions."""

from .baselines import (
    ELUAdapter,
    ELUConfig,
    LOWAdapter,
    LOWConfig,
    TAFAdapter,
    TAFConfig,
    WFRAdapter,
    WFRConfig,
)

from .contracts import (
    AdapterInput,
    MemoryUpdateAdapter,
    build_adapter_input,
    canonical_sha256,
    load_private_evaluation,
    load_public_observation,
    run_adapter,
    seal_candidate_catalog,
    seal_private_evaluation,
    seal_teacher_targets,
    validate_candidate_catalog,
    validate_memory_update_result,
    validate_observation_packet,
    validate_private_evaluation,
    validate_private_mutation_invariance,
    validate_teacher_targets,
)
from .causal_prior import (
    PublicBootstrapConfig,
    advance_public_bootstrap,
    build_causal_prior,
    empty_public_memory,
    validate_causal_prior_receipt,
)
from .public_candidates import (
    PublicCandidateConfig,
    generate_public_candidate_catalog,
    label_sealed_candidates,
)
from .vm04_protocol import (
    assert_vm04_action_authorized,
    make_episode_plan_manifests,
    make_family_split_manifest,
    reveal_confirmation_family_ids,
    validate_episode_plan_manifests,
    validate_family_split_manifest,
    validate_vm04_protocol,
)

__all__ = [
    "AdapterInput",
    "MemoryUpdateAdapter",
    "build_adapter_input",
    "canonical_sha256",
    "load_private_evaluation",
    "load_public_observation",
    "run_adapter",
    "seal_candidate_catalog",
    "seal_private_evaluation",
    "seal_teacher_targets",
    "validate_candidate_catalog",
    "validate_memory_update_result",
    "validate_observation_packet",
    "validate_private_evaluation",
    "validate_private_mutation_invariance",
    "validate_teacher_targets",
    "ELUAdapter",
    "ELUConfig",
    "LOWAdapter",
    "LOWConfig",
    "TAFAdapter",
    "TAFConfig",
    "WFRAdapter",
    "WFRConfig",
    "PublicCandidateConfig",
    "generate_public_candidate_catalog",
    "label_sealed_candidates",
    "PublicBootstrapConfig",
    "advance_public_bootstrap",
    "build_causal_prior",
    "empty_public_memory",
    "validate_causal_prior_receipt",
    "assert_vm04_action_authorized",
    "make_episode_plan_manifests",
    "make_family_split_manifest",
    "reveal_confirmation_family_ids",
    "validate_episode_plan_manifests",
    "validate_family_split_manifest",
    "validate_vm04_protocol",
]
