"""D-224-S1 ruling 49: the public camera pose of an S1-02 episode, read with the pitch sign restored.

The S1-02 generator's ``camera_pose`` (commit 3272d11 up to ruling 49) built the camera-to-world
rotation as Ry(yaw) * Rx(-pitch) while AI2-THOR's ``cameraHorizon`` is positive when the camera
looks down, so every public ``relative_pose.quaternion_xyzw`` it wrote points the camera up by the
pitch instead of down.  The D-223 back-projection reads the quaternion as a plain camera-to-world
rotation (the same convention the VM-04 worker encoded with +pitch), so it is the encoder that
deviated.  The generated episode files are never modified (S0-02 rule); instead every reader that
back-projects a public frame of an episode from a registered pre-ruling-49 commit applies the
exact inverse here:

    R_written = Ry(yaw) * Rx(-p)          forward_y = sin(p)      p = asin(forward_y)
    R_true    = R_written * Rx(2p) = Ry(yaw) * Rx(+p)

The position is untouched.  Episodes generated by a registered corrected encoder are read as they
are, and an episode from an unregistered commit is refused, so the correction can never be applied
twice or to data it was not ruled for.

白话：S1-02 写进公开帧的相机朝向把"低头 30 度"写成了"抬头 30 度"，位置没错。裁决 49 不改已生成
的文件，而是让每个要用位姿反投影的读者（S1-03 cache 生成、S1-04 几何残差与代理盒）在读取时把
俯仰角的符号翻回来：由四元数算出相机前向量，前向量的 y 分量就是 sin(俯仰角)，再右乘绕 x 轴
两倍俯仰角的旋转。只对合同登记的旧编码器提交生成的 episode 做；新编码器生成的照原样读；不在登
记表里的提交直接拒绝。它不是重新标定，也不改变任何私有真值。

Importable under Python 3.9 (the simulator environment) with numpy only.
"""

from __future__ import annotations

import math
from typing import Any, Mapping, Sequence

import numpy as np

#: The rule and correction as the S1-03 contract registers them (ruling 49).
DEFECT_ID = "s1_02_camera_pose_encoded_minus_pitch_camera_looked_up_when_the_agent_looked_down"
CORRECTION_RULE = "right_multiply_rx_of_twice_the_pitch_recovered_as_asin_of_forward_y"
POSE_KEYS = ("position_m", "quaternion_xyzw")
UNIT_TOLERANCE = 1e-6


class LeanPublicPoseError(ValueError):
    """Raised with a short machine-readable code."""


def _require(condition: bool, code: str) -> None:
    if not condition:
        raise LeanPublicPoseError(code)


def rotation_from_quaternion_xyzw(quaternion: Sequence[float]) -> np.ndarray:
    """Camera-to-world rotation matrix; the same formula the D-223 core (``_camera_values``) uses."""

    q = np.asarray([float(v) for v in quaternion], dtype=np.float64)
    _require(q.shape == (4,) and bool(np.isfinite(q).all()), "quaternion_invalid")
    _require(abs(float(np.linalg.norm(q)) - 1.0) <= UNIT_TOLERANCE, "quaternion_not_unit")
    x, y, z, w = q
    return np.asarray([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ], dtype=np.float64)


def quaternion_xyzw_from_rotation(rotation: np.ndarray) -> list[float]:
    """Unit quaternion (x, y, z, w) of a rotation matrix, w >= 0, by the standard branch rule."""

    r = np.asarray(rotation, dtype=np.float64)
    _require(r.shape == (3, 3) and bool(np.isfinite(r).all()), "rotation_invalid")
    _require(bool(np.allclose(r @ r.T, np.eye(3), atol=1e-9)) and abs(float(np.linalg.det(r)) - 1.0) < 1e-9,
             "rotation_not_orthonormal")
    trace = float(np.trace(r))
    if trace > 0.0:
        s = math.sqrt(trace + 1.0) * 2.0
        w, x, y, z = 0.25 * s, (r[2, 1] - r[1, 2]) / s, (r[0, 2] - r[2, 0]) / s, (r[1, 0] - r[0, 1]) / s
    else:
        i = int(np.argmax([r[0, 0], r[1, 1], r[2, 2]]))
        if i == 0:
            s = math.sqrt(1.0 + r[0, 0] - r[1, 1] - r[2, 2]) * 2.0
            w, x, y, z = (r[2, 1] - r[1, 2]) / s, 0.25 * s, (r[0, 1] + r[1, 0]) / s, (r[0, 2] + r[2, 0]) / s
        elif i == 1:
            s = math.sqrt(1.0 + r[1, 1] - r[0, 0] - r[2, 2]) * 2.0
            w, x, y, z = (r[0, 2] - r[2, 0]) / s, (r[0, 1] + r[1, 0]) / s, 0.25 * s, (r[1, 2] + r[2, 1]) / s
        else:
            s = math.sqrt(1.0 + r[2, 2] - r[0, 0] - r[1, 1]) * 2.0
            w, x, y, z = (r[1, 0] - r[0, 1]) / s, (r[0, 2] + r[2, 0]) / s, (r[1, 2] + r[2, 1]) / s, 0.25 * s
    q = np.asarray([x, y, z, w], dtype=np.float64)
    if q[3] < 0.0:
        q = -q
    q = q / float(np.linalg.norm(q))
    return [float(v) for v in q]


def rotation_x(angle_radians: float) -> np.ndarray:
    c, s = math.cos(angle_radians), math.sin(angle_radians)
    return np.asarray([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]], dtype=np.float64)


def camera_forward(quaternion: Sequence[float]) -> list[float]:
    """The camera's +z axis in the episode frame."""

    return [float(v) for v in rotation_from_quaternion_xyzw(quaternion)[:, 2]]


def recovered_pitch_radians(quaternion: Sequence[float]) -> float:
    """The pitch the pre-ruling-49 encoder wrote with the wrong sign: asin of forward_y."""

    forward_y = camera_forward(quaternion)[1]
    return math.asin(max(-1.0, min(1.0, forward_y)))


def corrected_quaternion_xyzw(quaternion: Sequence[float]) -> list[float]:
    """Ry(yaw) * Rx(-p) -> Ry(yaw) * Rx(+p): the written rotation right-multiplied by Rx(2p)."""

    rotation = rotation_from_quaternion_xyzw(quaternion)
    pitch = recovered_pitch_radians(quaternion)
    return quaternion_xyzw_from_rotation(rotation @ rotation_x(2.0 * pitch))


def correct_relative_pose(pose: Mapping[str, Any]) -> dict[str, Any]:
    """The pose with the pitch sign restored; the position is copied unchanged."""

    _require(all(key in pose for key in POSE_KEYS), "pose_keys_missing")
    return {"position_m": [float(v) for v in pose["position_m"]],
            "quaternion_xyzw": corrected_quaternion_xyzw(pose["quaternion_xyzw"])}


def correction_applies(code_commit: Any, policy: Mapping[str, Any]) -> bool:
    """Whether an episode generated at ``code_commit`` needs the correction, by the registered lists.

    ``policy`` is the S1-03 contract's ``public_pose_correction`` block.  A commit in
    ``applies_to_s1_02_code_commits`` is corrected, one in ``correct_encoder_since_code_commits``
    is read as written, and any other commit is refused: the rule is never guessed from the data.
    """

    _require(policy.get("rule") == CORRECTION_RULE, "policy_rule_mismatch")
    _require(isinstance(code_commit, str) and len(code_commit) == 40 and all(c in "0123456789abcdef" for c in code_commit),
             "episode_code_commit_invalid")
    defective = set(policy["applies_to_s1_02_code_commits"])
    corrected = set(policy["correct_encoder_since_code_commits"])
    _require(not (defective & corrected), "policy_commit_in_both_lists")
    if code_commit in defective:
        return True
    if code_commit in corrected:
        return False
    raise LeanPublicPoseError("episode_code_commit_not_registered:" + code_commit)


def public_camera_pose(record: Mapping[str, Any], *, code_commit: Any, policy: Mapping[str, Any]) -> dict[str, Any]:
    """The pose a reader must back-project a public frame with; the one entry point for every reader."""

    pose = record["relative_pose"]
    _require(all(key in pose for key in POSE_KEYS), "pose_keys_missing")
    if correction_applies(code_commit, policy):
        return correct_relative_pose(pose)
    return {"position_m": [float(v) for v in pose["position_m"]],
            "quaternion_xyzw": [float(v) for v in pose["quaternion_xyzw"]]}


__all__ = [
    "CORRECTION_RULE",
    "DEFECT_ID",
    "LeanPublicPoseError",
    "camera_forward",
    "correct_relative_pose",
    "corrected_quaternion_xyzw",
    "correction_applies",
    "public_camera_pose",
    "quaternion_xyzw_from_rotation",
    "recovered_pitch_radians",
    "rotation_from_quaternion_xyzw",
    "rotation_x",
]
