#!/usr/bin/env python3
"""S4: the paper's data tables, generated from the committed results so that no table number is copied by hand.

白话：论文正文里有两张数据表，都由这个脚本从 ``results/`` 里已提交的导出排出，写成 ``paper/tables/*.tex``：
- ``main.tex``：test 主表，两套前端 × 九个臂 × 九项指标，加已恢复／未恢复的变化物体数；列按“它回答哪个问题”分组。数取自 S3-05 统计
  （均值、种子标准差、每列保留的 house 数）与 S3-06 复算（恢复计数）。例如 VSMT-lean 的节点 F1 取自
  ``vsmt_lean_s3_05_statistics_8d58475.json`` 的 ``fronts.instance.main_table.node_prf1.VSMT-lean``。
- ``llm_op.tex``：LLM-op 小表，LLM-op 与其他各臂（S3-04 冻结配置）在同一条 validation episode 上的节点 F1 与假撤回率，
  以及这条 episode 在该臂全部 validation 里的百分位；数取自 S4 E1 导出 ``vsmt_lean_s4_llm_op_context_2b50a12.json``。
它不计算任何新的统计量，只排版。主门检验、逐指标比较与外部验证改由 ``make_figures.py`` 画成图；原附录里的选参、三分解与规模表
不再进论文（RA-L 的 8 页含附录），其数在正文里引用，全表留在已提交的导出与 README 的论文索引里。

Usage (repository root): python paper/tools/make_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "results"
OUT = ROOT / "paper" / "tables"
STATISTICS = "vsmt_lean_s3_05_statistics_8d58475.json"
REANALYSIS = "vsmt_lean_s3_06_reanalysis_cd3ee83.json"
LLM_OP_CONTEXT = "vsmt_lean_s4_llm_op_context_2b50a12.json"

ARMS = ("VSMT-lean", "AssocOnly", "NoVersion", "HeuristicLabel", "HandCost", "TAF", "ELU-P", "RAC", "LOW")
FRONTS = (("instance", "Simulator instance masks"), ("sam2", "SAM 2.1 masks"))
#: (metric key, column header, decimals); a down arrow marks metrics where lower is better, bold the two primary metrics
METRICS = (
    ("node_prf1", r"F1", 3),
    ("node_prf1_iou", r"F1$_{\mathrm{IoU}}$", 3),
    ("missing_residual_rate", r"\textbf{MRR}$\downarrow$", 3),
    ("false_retract_rate", r"FRR$\downarrow$", 3),
    ("false_retract_rate_in_scope", r"FRR$_{\mathrm{in}}\!\downarrow$", 3),
    ("identity_continuity", r"\textbf{IdC}", 3),
    ("retrieval_success", r"Retr.", 3),
    ("recovery_latency_frames", r"Lat.$\downarrow$", 1),
    ("contamination_auc", r"Cont.$\downarrow$", 3),
)
#: main-table columns in reading order, grouped by the question each answers; None marks the recovered/unrecovered counts
MAIN_GROUPS = (
    ("Node accuracy", ("node_prf1", "node_prf1_iou")),
    ("Stale", ("missing_residual_rate",)),
    ("False retractions", ("false_retract_rate_in_scope", "false_retract_rate")),
    ("Relocated objects", ("identity_continuity", "retrieval_success")),
    ("Recovery", ("recovery_latency_frames", None)),
    ("Contamination", ("contamination_auc",)),
)
HEADER = "% generated by paper/tools/make_tables.py from results/{}; do not edit by hand\n"


def load(name: str) -> Any:
    return json.loads((RESULTS / name).read_text(encoding="utf-8"))


def number(value: float | None, decimals: int = 3) -> str:
    return "--" if value is None else f"{value:.{decimals}f}"


def short(value: float, decimals: int) -> str:
    """A seed SD without its leading zero, so that the main table fits the page width."""

    text = f"{value:.{decimals}f}"
    return text[1:] if text.startswith("0.") else text


def mean_cell(entry: Mapping[str, Any] | None, decimals: int) -> str:
    """A main-table cell: the mean, with the seed SD for learned arms and the seed count when fewer than five had a value."""

    if not entry or entry.get("not_applicable") or entry.get("mean") is None:
        return "--"
    text = number(entry["mean"], decimals)
    if entry.get("sd") is not None:
        text += r"{\tiny$\pm$" + short(entry["sd"], decimals) + "}"
    seeds = entry.get("seeds_with_values")
    if seeds is not None and seeds != 5:
        text += rf"$^{{({seeds})}}$"
    return text


def recovery_counts(reanalysis: Mapping[str, Any], front: str, arm: str) -> str:
    """Recovered / unrecovered changed objects over every usable episode (D4 ``per_arm_all_houses``)."""

    entry = reanalysis["d4_counts"][front]["recovery_latency_frames"]["per_arm_all_houses"][arm]
    counts = entry.get("mean", entry)
    return f"{counts['recovered']:g}/{counts['unrecovered']:g}"


def main_table(stats: Mapping[str, Any], reanalysis: Mapping[str, Any]) -> str:
    """The main results table: both front ends, nine arms, nine metric columns plus recovered/unrecovered counts,
    with the columns grouped by the question they answer and the arms grouped as proposed, ablations, rule-based."""

    specs = {key: (header, decimals) for key, header, decimals in METRICS}
    keys = [key for _, group in MAIN_GROUPS for key in group]
    columns = len(keys) + 1
    groups, rules, start = [], [], 2
    for title, group in MAIN_GROUPS:
        groups.append(rf"\multicolumn{{{len(group)}}}{{c}}{{{title}}}")
        rules.append(rf"\cmidrule(lr){{{start}-{start + len(group) - 1}}}")
        start += len(group)
    headers = [specs[key][0] if key else "Rec./unrec." for key in keys]
    lines = [HEADER.format(f"{STATISTICS} and {REANALYSIS}"), r"\begin{tabular}{l" + "c" * (columns - 1) + "}", r"\toprule",
             " & " + " & ".join(groups) + r" \\", "".join(rules), "Arm & " + " & ".join(headers) + r" \\"]
    for front, title in FRONTS:
        block = stats["fronts"][front]
        lines += [r"\midrule", rf"\multicolumn{{{columns}}}{{l}}{{\emph{{{title}}} ({block['episodes']} test houses)}} \\"]
        for arm in ARMS:
            if arm in ("AssocOnly", "TAF"):
                lines.append(r"\addlinespace[1.5pt]")
            name = rf"\textbf{{{arm}}}" if arm == "VSMT-lean" else arm
            cells = [recovery_counts(reanalysis, front, arm) if key is None
                     else mean_cell(block["main_table"][key].get(arm), specs[key][1]) for key in keys]
            lines.append(name + " & " + " & ".join(cells) + r" \\")
        houses = ["all" if key is None else str(block["exclusion_lists"][key]["effective_houses"]) for key in keys]
        lines.append(r"\addlinespace[1.5pt]")
        lines.append(r"\emph{Houses kept} & " + " & ".join(houses) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def llm_op_value(entry: Mapping[str, Any], percentile: bool) -> str:
    """An arm's value on the LLM-op episode (E1); with ``percentile``, also this episode's percentile among the arm's own
    validation episodes. n/d: undefined on this episode for at least one seed; --: the arm never retracts."""

    if entry["episodes_defined"] == 0:
        return "--"
    if entry["episode_value"] is None:
        return "n/d"
    text = number(entry["episode_value"])
    if percentile and entry["episode_percentile"] is not None:
        text += rf"{{\tiny\,(p{entry['episode_percentile']:.0f})}}"
    return text


def llm_op_table(context: Mapping[str, Any]) -> str:
    """The small LLM-op table of the main text: node F1 and false-retract rate of LLM-op and of every other arm (frozen
    configuration) on the one LLM-op validation episode per front end (E1; descriptive, n = 1 per front end)."""

    keys = (("node_f1", "F1", True), ("false_retract_rate", r"FRR$\downarrow$", False))
    lines = [HEADER.format(LLM_OP_CONTEXT), r"\begin{tabular}{l" + "cc" * len(FRONTS) + "}", r"\toprule",
             " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{title}}}" for _, title in FRONTS) + r" \\",
             r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
             "Arm & " + " & ".join(header for _ in FRONTS for _, header, _ in keys) + r" \\", r"\midrule"]
    blocks = [context["fronts"][front] for front, _ in FRONTS]
    if len({block["episode_id"] for block in blocks}) != 1:
        raise SystemExit("the LLM-op episode differs between front ends")
    lines.append(r"\textbf{LLM-op} & " + " & ".join(number(block["llm_op"][key]) for block in blocks for key, _, _ in keys)
                 + r" \\")
    lines.append(r"\addlinespace[1.5pt]")
    for arm in ARMS:
        lines.append(arm + " & " + " & ".join(llm_op_value(block["arms"][arm][key], percentile)
                                              for block in blocks for key, _, percentile in keys) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    stats, reanalysis = load(STATISTICS), load(REANALYSIS)
    OUT.mkdir(parents=True, exist_ok=True)
    tables = {"main.tex": main_table(stats, reanalysis), "llm_op.tex": llm_op_table(load(LLM_OP_CONTEXT))}
    for name, text in tables.items():
        with open(OUT / name, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print(f"paper/tables/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
