#!/usr/bin/env python3
"""S4: the paper's tables, generated from the committed results so that no table number is copied by hand.

白话：论文里的每张表都由这个脚本从 ``results/`` 里已提交的导出排出——S3-05 统计（主表、主门、对各对照的比较与种子稳定性）、
S3-06 复算（双侧 90% 区间、事件计数、三分解占比、规模）、S3-07 外部验证（3RScan 实例分割列）、S3-04 冻结回执（每臂唯一配置）、S4 E1 导出（LLM-op 那条 episode 上各臂的值）——写成 ``paper/tables/*.tex``。
输入只有这些 JSON；输出是 LaTeX 表格片段。例如主表 VSMT-lean 的节点 F1 取自
``vsmt_lean_s3_05_statistics_8d58475.json`` 的 ``fronts.instance.main_table.node_prf1.VSMT-lean``。它不计算任何新的统计量，
只排版；区间、优势与计数都是导出里已有的数（三分解只把已导出的占比乘 100）。

Usage (repository root): python paper/tools/make_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "results"
OUT = ROOT / "paper" / "tables"
STATISTICS = "vsmt_lean_s3_05_statistics_8d58475.json"
REANALYSIS = "vsmt_lean_s3_06_reanalysis_cd3ee83.json"
EXTERNAL = "vsmt_lean_s3_07_statistics_aa94373.json"
FREEZE = "vsmt_lean_s3_04_freeze_dea8c20.json"
LLM_OP_CONTEXT = "vsmt_lean_s4_llm_op_context_2b50a12.json"

ARMS = ("VSMT-lean", "AssocOnly", "NoVersion", "HeuristicLabel", "HandCost", "TAF", "ELU-P", "RAC", "LOW")
ABLATIONS = ("AssocOnly", "NoVersion", "HeuristicLabel", "HandCost")
RULE_ARMS = ("TAF", "ELU-P", "RAC", "LOW")
FRONTS = (("instance", "Simulator instance masks"), ("sam2", "SAM 2.1 masks"))
#: (metric key, column header, decimals); a down arrow marks metrics where lower is better
METRICS = (
    ("node_prf1", r"F1", 3),
    ("node_prf1_iou", r"F1$_{\mathrm{IoU}}$", 3),
    ("missing_residual_rate", r"MRR$\downarrow$", 3),
    ("false_retract_rate", r"FRR$\downarrow$", 3),
    ("false_retract_rate_in_scope", r"FRR$_{\mathrm{in}}\!\downarrow$", 3),
    ("identity_continuity", r"IdC", 3),
    ("retrieval_success", r"Retr.", 3),
    ("recovery_latency_frames", r"Lat.$\downarrow$", 1),
    ("contamination_auc", r"Cont.$\downarrow$", 3),
)
GATE_METRICS = (("missing_residual_rate", "MRR"), ("identity_continuity", "IdC"))
HEADER = "% generated by paper/tools/make_tables.py from results/{}; do not edit by hand\n"


def load(name: str) -> Any:
    return json.loads((RESULTS / name).read_text(encoding="utf-8"))


def number(value: float | None, decimals: int = 3) -> str:
    return "--" if value is None else f"{value:.{decimals}f}"


def signed(value: float | None, decimals: int = 3) -> str:
    """A signed number; a value that rounds to zero is printed unsigned rather than as +0.000 or -0.000."""

    if value is None:
        return "--"
    if round(value, decimals) == 0:
        return f"{0:.{decimals}f}"
    return f"{value:+.{decimals}f}".replace("-", "$-$")


def short(value: float, decimals: int) -> str:
    """A seed SD without its leading zero, so that the main table fits the page width."""

    text = f"{value:.{decimals}f}"
    return text[1:] if text.startswith("0.") else text


def mean_cell(entry: Mapping[str, Any] | None, decimals: int) -> str:
    """A main-table cell: the mean, with the seed SD for learned arms and the seed count when fewer than five had a value."""

    if not entry or entry.get("not_applicable") or entry.get("mean") is None:
        return "--"
    text = number(entry["mean"], decimals)
    if entry.get("sd") is not None:
        text += r"{\tiny$\pm$" + short(entry["sd"], decimals) + "}"
    seeds = entry.get("seeds_with_values")
    if seeds is not None and seeds != 5:
        text += rf"$^{{({seeds})}}$"
    return text


def advantage_cell(advantage: float | None, interval: list[float] | None, stable: bool | None, decimals: int) -> str:
    if advantage is None or interval is None:
        return "--"
    mark = r"$^{\ast}$" if stable else ""
    return (f"{signed(advantage, decimals)}{mark} "
            f"{{\\tiny[{signed(interval[0], decimals)}, {signed(interval[1], decimals)}]}}")


def recovery_counts(reanalysis: Mapping[str, Any], front: str, arm: str) -> str:
    """Recovered / unrecovered relocated objects over every usable episode (D4 ``per_arm_all_houses``)."""

    entry = reanalysis["d4_counts"][front]["recovery_latency_frames"]["per_arm_all_houses"][arm]
    counts = entry.get("mean", entry)
    return f"{counts['recovered']:g}/{counts['unrecovered']:g}"


def main_table(stats: Mapping[str, Any], reanalysis: Mapping[str, Any]) -> str:
    """Table I: both front ends, nine arms, nine metric columns plus recovered/unrecovered counts."""

    columns = len(METRICS) + 2
    lines = [HEADER.format(f"{STATISTICS} and {REANALYSIS}"), r"\begin{tabular}{l" + "c" * (columns - 1) + "}", r"\toprule",
             "Arm & " + " & ".join(header for _, header, _ in METRICS) + r" & Rec./unrec. \\"]
    for front, title in FRONTS:
        block = stats["fronts"][front]
        lines += [r"\midrule", rf"\multicolumn{{{columns}}}{{l}}{{\emph{{{title}}} ({block['episodes']} test houses)}} \\"]
        for arm in ARMS:
            name = rf"\textbf{{{arm}}}" if arm == "VSMT-lean" else arm
            cells = [mean_cell(block["main_table"][key].get(arm), decimals) for key, _, decimals in METRICS]
            lines.append(name + " & " + " & ".join(cells) + " & " + recovery_counts(reanalysis, front, arm) + r" \\")
        houses = [str(block["exclusion_lists"][key]["effective_houses"]) for key, _, _ in METRICS]
        lines.append(r"\emph{Houses kept} & " + " & ".join(houses) + r" & all \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def gate_row(label: str, block: Mapping[str, Any], arm_mean: float, control_mean: float, step: str) -> str:
    favourable = sum(1 for gap in block["seed_paired_gaps"] if gap > 0)
    holds = r"\textbf{yes}" if block["passed"] else "no"
    return (f"{step} & {label} & {number(arm_mean)} & {number(control_mean)} & {signed(block['mean_advantage'])} & "
            f"{signed(block['lower_bound_two_level'])} & {favourable}/5 & {'yes' if block['stable_82_1'] else 'no'} & "
            f"{block['houses']} & {holds}" + r" \\")


def gate_table(stats: Mapping[str, Any]) -> str:
    """Table II: the pre-registered fixed sequence against AssocOnly, then the original gate (reported only)."""

    plan = (("1", "instance", "missing_residual_rate"), ("1", "instance", "identity_continuity"),
            ("2", "sam2", "missing_residual_rate"), ("3", "sam2", "identity_continuity"))
    labels = {"instance": "Inst.", "sam2": "SAM 2.1"}
    metric_names = dict(GATE_METRICS)
    lines = [HEADER.format(STATISTICS), r"\begin{tabular}{clcccccccc}", r"\toprule",
             r"Step & Front end / metric & VSMT-lean & Control & Adv. & LB & Fav. & 82-1 & Houses & Holds \\", r"\midrule",
             r"\multicolumn{10}{l}{\emph{Primary hypothesis: VSMT-lean vs.\ AssocOnly, fixed testing order}} \\"]
    for step, front, metric in plan:
        block = stats["fronts"][front]["primary_gate"]["metrics"][metric]
        table = stats["fronts"][front]["main_table"][metric]
        lines.append(gate_row(f"{labels[front]} / {metric_names[metric]}", block, table["VSMT-lean"]["mean"],
                              table["AssocOnly"]["mean"], step))
    lines += [r"\midrule", r"\multicolumn{10}{l}{\emph{Original gate: VSMT-lean vs.\ the strongest rule-based control "
              r"per metric (reported, not gating)}} \\"]
    for front, _ in FRONTS:
        for metric, name in GATE_METRICS:
            block = stats["fronts"][front]["original_gate"]["metrics"][metric]
            control = block["strongest_control"]
            table = stats["fronts"][front]["main_table"][metric]
            lines.append(gate_row(f"{labels[front]} / {name} vs.\\ {control}", block, table["VSMT-lean"]["mean"],
                                  table[control]["mean"], "--"))
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def stability(stats: Mapping[str, Any], reanalysis: Mapping[str, Any], front: str, metric: str, control: str) -> bool | None:
    if control == "AssocOnly":
        block = reanalysis["d2_assoc_only"]["per_front"][front].get(metric)
    else:
        block = stats["fronts"][front]["comparisons"].get(metric, {}).get(control)
    return None if not block else block.get("stable_82_1")


def comparison_table(stats: Mapping[str, Any], reanalysis: Mapping[str, Any], controls: tuple[str, ...]) -> str:
    """Tables III/IV: VSMT-lean against each control, every metric, advantage with the two-level 90% interval."""

    lines = [HEADER.format(f"{REANALYSIS} (intervals) and {STATISTICS} (seed stability)"),
             r"\begin{tabular}{l" + "c" * len(controls) + "}", r"\toprule", "Metric & " + " & ".join(controls) + r" \\"]
    for front, title in FRONTS:
        intervals = reanalysis["d3_intervals"][front]
        lines += [r"\midrule", rf"\multicolumn{{{len(controls) + 1}}}{{l}}{{\emph{{{title}}}}} \\"]
        for key, header, decimals in METRICS:
            cells = []
            for control in controls:
                entry = intervals.get(key, {}).get(control)
                cells.append("--" if entry is None else advantage_cell(
                    entry["mean_advantage"], entry["interval_90"], stability(stats, reanalysis, front, key, control), decimals))
            lines.append(header + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def external_table(external: Mapping[str, Any]) -> str:
    """Table V: 3RScan validation, instance column; means, kept scenes, and VSMT-lean vs. AssocOnly with the 90% interval."""

    front = external["fronts"]["instance"]
    table, lists, comparisons = front["main_table"], front["exclusion_lists"], front["comparisons"]
    lines = [HEADER.format(EXTERNAL), r"\begin{tabular}{l" + "c" * len(METRICS) + "}", r"\toprule",
             "Arm & " + " & ".join(header for _, header, _ in METRICS) + r" \\", r"\midrule"]
    for arm in ARMS:
        name = rf"\textbf{{{arm}}}" if arm == "VSMT-lean" else arm
        lines.append(name + " & " + " & ".join(mean_cell(table[key].get(arm), decimals) for key, _, decimals in METRICS) + r" \\")
    lines.append(r"\emph{Scenes kept} & " + " & ".join(str(lists[key]["effective_scenes"]) for key, _, _ in METRICS) + r" \\")
    lines.append(r"\midrule")
    advantages, intervals = [], []
    for key, _, decimals in METRICS:
        entry = comparisons[key].get("AssocOnly", {})
        if entry.get("not_applicable") or "interval_90" not in entry:
            advantages.append("--")
            intervals.append("")
            continue
        advantages.append(signed(entry["mean_advantage"], decimals) + (r"$^{\ast}$" if entry.get("stable_82_1") else ""))
        low, high = entry["interval_90"]
        intervals.append(r"{\tiny[" + f"{signed(low, decimals)}, {signed(high, decimals)}" + "]}")
    lines.append(r"\emph{Adv.\ vs.\ AssocOnly} & " + " & ".join(advantages) + r" \\")
    lines.append(r"\emph{\quad 90\% interval} & " + " & ".join(intervals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def llm_op_cell(entry: Mapping[str, Any]) -> str:
    """An arm's value on the LLM-op episode, then its validation mean and SD and this episode's percentile (E1)."""

    value = entry["episode_value"]
    if entry["episodes_defined"] == 0:
        return "--"
    head = "n/d" if value is None else number(value)
    tail = number(entry["validation_mean"]) + r"$\pm$" + short(entry["validation_sd"], 3)
    if entry["episode_percentile"] is not None:
        tail += f"; p{entry['episode_percentile']:.0f}"
    return head + r"{\tiny\,(" + tail + ")}"


def llm_op_table(context: Mapping[str, Any]) -> str:
    """Supplementary table: LLM-op and every other arm on the one LLM-op validation episode (E1, descriptive, n = 1)."""

    keys = (("node_f1", "F1"), ("node_f1_iou", r"F1$_{\mathrm{IoU}}$"), ("false_retract_rate", r"FRR$\downarrow$"),
            ("contamination_auc", r"Cont.$\downarrow$"))
    lines = [HEADER.format(LLM_OP_CONTEXT), r"\begin{tabular}{l" + "c" * len(keys) + "}", r"\toprule",
             "Arm & " + " & ".join(header for _, header in keys) + r" \\"]
    for front, title in FRONTS:
        block = context["fronts"][front]
        episode = block["episode"]
        lines += [r"\midrule", rf"\multicolumn{{{len(keys) + 1}}}{{l}}{{\emph{{{title}}}: {episode['frames']} frames "
                  rf"(p{episode['frames_percentile']:.0f}), {episode['fragments_per_frame']:.1f} fragments per frame "
                  rf"(p{episode['fragments_per_frame_percentile']:.0f})}} \\"]
        lines.append(r"\textbf{LLM-op} & " + " & ".join(number(block["llm_op"][key]) for key, _ in keys) + r" \\")
        for arm in ARMS:
            lines.append(arm + " & " + " & ".join(llm_op_cell(block["arms"][arm][key]) for key, _ in keys) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def decomposition_table(reanalysis: Mapping[str, Any]) -> str:
    """Supplementary table: the decision ledger per arm (D6), shares of each arm's own decisions, pooled over seeds."""

    names = ("recall_miss", "teacher_error", "amortization_error", "duplicate_of_labelled", "correct")
    lines = [HEADER.format(REANALYSIS), r"\begin{tabular}{lrrrrrr}", r"\toprule",
             r"Arm & Decisions/run & Recall miss & Teacher err. & Amort.\ err. & Duplicate & Correct \\"]
    for front, title in FRONTS:
        per_arm = reanalysis["d6_decomposition"][front]["per_arm"]
        lines += [r"\midrule", rf"\multicolumn{{7}}{{l}}{{\emph{{{title}}} (\% of the arm's own decisions)}} \\"]
        for arm in ARMS:
            entry = per_arm[arm]
            shares = " & ".join(f"{100 * entry['shares'][name]:.1f}" for name in names)
            lines.append(f"{arm} & {entry['per_run_mean']['decisions'] / 1e6:.2f}\\,M & {shares}" + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def size_table(reanalysis: Mapping[str, Any]) -> str:
    """Supplementary table: memory size (D7), episode means averaged over seeds; runtime is left out (not comparable)."""

    lines = [HEADER.format(REANALYSIS), r"\begin{tabular}{lrrrrrr}", r"\toprule",
             r" & \multicolumn{3}{c}{Simulator instance masks} & \multicolumn{3}{c}{SAM 2.1 masks} \\",
             r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
             r"Arm & Active & Versions & Peak MB & Active & Versions & Peak MB \\", r"\midrule"]
    for arm in ARMS:
        cells = []
        for front, _ in FRONTS:
            entry = reanalysis["d7_size_and_cost"][front]["per_arm"][arm]
            cells += [f"{entry['active_entity_count']['mean']:.1f}", f"{entry['lifecycle_version_count']['mean']:,.0f}",
                      f"{entry['peak_memory_bytes']['mean'] / 1e6:,.0f}"]
        lines.append(arm + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


PARAMETERS = {"tau_r": r"\tau_r", "theta_a": r"\theta_a", "d_a": "d_a", "free_space_weight": "w_f",
              "retract_threshold": r"\ell_r", "rho_rac": r"\rho_{\mathrm{rac}}", "n_rac": r"n_{\mathrm{rac}}", "d_low": "d_{\\mathrm{low}}",
              "theta_b": r"\theta_b", "rho_h": r"\rho_h"}


def selection_table(freeze: Mapping[str, Any]) -> str:
    """Supplementary table: the one configuration per arm and front end (S3-04 freeze) with its validation node F1 and MRR;
    a dagger marks a value at the end of its registered grid."""

    lines = [HEADER.format(FREEZE), r"\begin{tabular}{llcc}", r"\toprule", r"Arm & Selected configuration & Val.\ F1 & Val.\ MRR \\"]
    for front, title in FRONTS:
        selection = freeze["fronts"][front]["selection"]
        lines += [r"\midrule", rf"\multicolumn{{4}}{{l}}{{\emph{{{title}}}}} \\"]
        for arm in ARMS:
            entry = selection["arms"][arm]
            edges = {edge["parameter"] for edge in entry["grid_edge"]}
            config = ", ".join(f"${PARAMETERS[key]}={value:g}" + (r"^{\dagger}$" if key in edges else "$")
                               for key, value in entry["config"].items()) or "(no parameter)"
            means = entry["validation_mean"]
            lines.append(f"{arm} & {config} & {number(means['node_prf1'])} & {number(means['missing_residual_rate'])}" + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    stats, reanalysis, external = load(STATISTICS), load(REANALYSIS), load(EXTERNAL)
    OUT.mkdir(parents=True, exist_ok=True)
    tables = {"main.tex": main_table(stats, reanalysis), "gate.tex": gate_table(stats),
              "ablations.tex": comparison_table(stats, reanalysis, ABLATIONS),
              "rule_arms.tex": comparison_table(stats, reanalysis, RULE_ARMS), "external.tex": external_table(external),
              "decomposition.tex": decomposition_table(reanalysis), "size.tex": size_table(reanalysis),
              "selection.tex": selection_table(load(FREEZE)), "llm_op.tex": llm_op_table(load(LLM_OP_CONTEXT))}
    for name, text in tables.items():
        with open(OUT / name, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print(f"paper/tables/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
